# Generated by Django 5.2.1 on 2025-05-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='searchhistory',
            name='weather_app_session_ac6cda_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchhistory',
            name='weather_app_user_id_6f6117_idx',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='count',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
